### ISSUE TITLE
`typeorm` ColumnTypeUndefinedError

### ISSUE THREAD

**Issue by hdmun** [hdmun/server-agent-admin#3]
```
 ERROR  ServerMiddleware Error: Column type for HostServer#hostName is not defined and cannot be guessed. Make sure you have turned on an "emitDecoratorMetadata": true option in tsconfig.json. Also make sure you have imported "reflect-metadata" on top of the main entry file in your application (before any entity imported).If you are using JavaScript instead of TypeScript you must explicitly provide a column type.

  at ColumnTypeUndefinedError.TypeORMError [as constructor] (node_modules\typeorm\error\TypeORMError.js:9:28)
  at new ColumnTypeUndefinedError (node_modules\typeorm\error\ColumnTypeUndefinedError.js:13:23)
  at node_modules\typeorm\decorator\columns\PrimaryColumn.js:33:19
  at serverMiddleware\entity\hostServer.ts:2:500
  at Array.reduce (<anonymous>)
  at _applyDecoratedDescriptor (serverMiddleware\entity\hostServer.ts:2:458)
  at serverMiddleware\entity\hostServer.ts:10:76
  at jiti (node_modules\jiti\dist\jiti.js:1:196506)
  at serverMiddleware\controller\hostController.ts:5:19
  at jiti (node_modules\jiti\dist\jiti.js:1:196506)
```

**Comment by hdmun** [comment]
`nuxt.config.js`에서 `serverMiddleware` 설정을 버리고 
별도 api express 서버 구조로 해결

**Comment by hdmun** [comment]
`serverMiddleware` 에서 왜 처리가 안되는지 궁금하다. 이건 시간 날 때 방법을 찾아보자.
